# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /tools/modulesystem/tools/cmake/cmake-2.8.11/install/sled11.x86_64.gcc-4.3.4.release/bin/cmake

# The command to remove a file.
RM = /tools/modulesystem/tools/cmake/cmake-2.8.11/install/sled11.x86_64.gcc-4.3.4.release/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /tools/modulesystem/tools/cmake/cmake-2.8.11/install/sled11.x86_64.gcc-4.3.4.release/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home_local/matu_gr/work/cresta/ppstee/trunk

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home_local/matu_gr/work/cresta/ppstee/trunk

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/tools/modulesystem/tools/cmake/cmake-2.8.11/install/sled11.x86_64.gcc-4.3.4.release/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/tools/modulesystem/tools/cmake/cmake-2.8.11/install/sled11.x86_64.gcc-4.3.4.release/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/tools/modulesystem/tools/cmake/cmake-2.8.11/install/sled11.x86_64.gcc-4.3.4.release/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/tools/modulesystem/tools/cmake/cmake-2.8.11/install/sled11.x86_64.gcc-4.3.4.release/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/tools/modulesystem/tools/cmake/cmake-2.8.11/install/sled11.x86_64.gcc-4.3.4.release/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/tools/modulesystem/tools/cmake/cmake-2.8.11/install/sled11.x86_64.gcc-4.3.4.release/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/tools/modulesystem/tools/cmake/cmake-2.8.11/install/sled11.x86_64.gcc-4.3.4.release/bin/cpack --config ./CPackSourceConfig.cmake /home_local/matu_gr/work/cresta/ppstee/trunk/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/tools/modulesystem/tools/cmake/cmake-2.8.11/install/sled11.x86_64.gcc-4.3.4.release/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/tools/modulesystem/tools/cmake/cmake-2.8.11/install/sled11.x86_64.gcc-4.3.4.release/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home_local/matu_gr/work/cresta/ppstee/trunk/CMakeFiles /home_local/matu_gr/work/cresta/ppstee/trunk/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home_local/matu_gr/work/cresta/ppstee/trunk/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) -f CMakeFiles/check.dir/build.make CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named check-style

# Build rule for target.
check-style: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-style
.PHONY : check-style

# fast build rule for target.
check-style/fast:
	$(MAKE) -f CMakeFiles/check-style.dir/build.make CMakeFiles/check-style.dir/build
.PHONY : check-style/fast

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f CMakeFiles/doc.dir/build.make CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named ppstee

# Build rule for target.
ppstee: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ppstee
.PHONY : ppstee

# fast build rule for target.
ppstee/fast:
	$(MAKE) -f CMakeFiles/ppstee.dir/build.make CMakeFiles/ppstee.dir/build
.PHONY : ppstee/fast

#=============================================================================
# Target rules for targets named ppstee_example

# Build rule for target.
ppstee_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ppstee_example
.PHONY : ppstee_example

# fast build rule for target.
ppstee_example/fast:
	$(MAKE) -f CMakeFiles/ppstee_example.dir/build.make CMakeFiles/ppstee_example.dir/build
.PHONY : ppstee_example/fast

#=============================================================================
# Target rules for targets named ppstee_test_113

# Build rule for target.
ppstee_test_113: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ppstee_test_113
.PHONY : ppstee_test_113

# fast build rule for target.
ppstee_test_113/fast:
	$(MAKE) -f CMakeFiles/ppstee_test_113.dir/build.make CMakeFiles/ppstee_test_113.dir/build
.PHONY : ppstee_test_113/fast

#=============================================================================
# Target rules for targets named ppstee_test_3

# Build rule for target.
ppstee_test_3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ppstee_test_3
.PHONY : ppstee_test_3

# fast build rule for target.
ppstee_test_3/fast:
	$(MAKE) -f CMakeFiles/ppstee_test_3.dir/build.make CMakeFiles/ppstee_test_3.dir/build
.PHONY : ppstee_test_3/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

examples/ppstee_example.o: examples/ppstee_example.cpp.o
.PHONY : examples/ppstee_example.o

# target to build an object file
examples/ppstee_example.cpp.o:
	$(MAKE) -f CMakeFiles/ppstee_example.dir/build.make CMakeFiles/ppstee_example.dir/examples/ppstee_example.cpp.o
.PHONY : examples/ppstee_example.cpp.o

examples/ppstee_example.i: examples/ppstee_example.cpp.i
.PHONY : examples/ppstee_example.i

# target to preprocess a source file
examples/ppstee_example.cpp.i:
	$(MAKE) -f CMakeFiles/ppstee_example.dir/build.make CMakeFiles/ppstee_example.dir/examples/ppstee_example.cpp.i
.PHONY : examples/ppstee_example.cpp.i

examples/ppstee_example.s: examples/ppstee_example.cpp.s
.PHONY : examples/ppstee_example.s

# target to generate assembly for a file
examples/ppstee_example.cpp.s:
	$(MAKE) -f CMakeFiles/ppstee_example.dir/build.make CMakeFiles/ppstee_example.dir/examples/ppstee_example.cpp.s
.PHONY : examples/ppstee_example.cpp.s

src/ppstee.o: src/ppstee.cpp.o
.PHONY : src/ppstee.o

# target to build an object file
src/ppstee.cpp.o:
	$(MAKE) -f CMakeFiles/ppstee.dir/build.make CMakeFiles/ppstee.dir/src/ppstee.cpp.o
.PHONY : src/ppstee.cpp.o

src/ppstee.i: src/ppstee.cpp.i
.PHONY : src/ppstee.i

# target to preprocess a source file
src/ppstee.cpp.i:
	$(MAKE) -f CMakeFiles/ppstee.dir/build.make CMakeFiles/ppstee.dir/src/ppstee.cpp.i
.PHONY : src/ppstee.cpp.i

src/ppstee.s: src/ppstee.cpp.s
.PHONY : src/ppstee.s

# target to generate assembly for a file
src/ppstee.cpp.s:
	$(MAKE) -f CMakeFiles/ppstee.dir/build.make CMakeFiles/ppstee.dir/src/ppstee.cpp.s
.PHONY : src/ppstee.cpp.s

src/ppstee_error.o: src/ppstee_error.cpp.o
.PHONY : src/ppstee_error.o

# target to build an object file
src/ppstee_error.cpp.o:
	$(MAKE) -f CMakeFiles/ppstee.dir/build.make CMakeFiles/ppstee.dir/src/ppstee_error.cpp.o
.PHONY : src/ppstee_error.cpp.o

src/ppstee_error.i: src/ppstee_error.cpp.i
.PHONY : src/ppstee_error.i

# target to preprocess a source file
src/ppstee_error.cpp.i:
	$(MAKE) -f CMakeFiles/ppstee.dir/build.make CMakeFiles/ppstee.dir/src/ppstee_error.cpp.i
.PHONY : src/ppstee_error.cpp.i

src/ppstee_error.s: src/ppstee_error.cpp.s
.PHONY : src/ppstee_error.s

# target to generate assembly for a file
src/ppstee_error.cpp.s:
	$(MAKE) -f CMakeFiles/ppstee.dir/build.make CMakeFiles/ppstee.dir/src/ppstee_error.cpp.s
.PHONY : src/ppstee_error.cpp.s

src/ppstee_objects.o: src/ppstee_objects.cpp.o
.PHONY : src/ppstee_objects.o

# target to build an object file
src/ppstee_objects.cpp.o:
	$(MAKE) -f CMakeFiles/ppstee.dir/build.make CMakeFiles/ppstee.dir/src/ppstee_objects.cpp.o
.PHONY : src/ppstee_objects.cpp.o

src/ppstee_objects.i: src/ppstee_objects.cpp.i
.PHONY : src/ppstee_objects.i

# target to preprocess a source file
src/ppstee_objects.cpp.i:
	$(MAKE) -f CMakeFiles/ppstee.dir/build.make CMakeFiles/ppstee.dir/src/ppstee_objects.cpp.i
.PHONY : src/ppstee_objects.cpp.i

src/ppstee_objects.s: src/ppstee_objects.cpp.s
.PHONY : src/ppstee_objects.s

# target to generate assembly for a file
src/ppstee_objects.cpp.s:
	$(MAKE) -f CMakeFiles/ppstee.dir/build.make CMakeFiles/ppstee.dir/src/ppstee_objects.cpp.s
.PHONY : src/ppstee_objects.cpp.s

test/MainSystemTest.o: test/MainSystemTest.cpp.o
.PHONY : test/MainSystemTest.o

# target to build an object file
test/MainSystemTest.cpp.o:
	$(MAKE) -f CMakeFiles/ppstee_test_113.dir/build.make CMakeFiles/ppstee_test_113.dir/test/MainSystemTest.cpp.o
	$(MAKE) -f CMakeFiles/ppstee_test_3.dir/build.make CMakeFiles/ppstee_test_3.dir/test/MainSystemTest.cpp.o
.PHONY : test/MainSystemTest.cpp.o

test/MainSystemTest.i: test/MainSystemTest.cpp.i
.PHONY : test/MainSystemTest.i

# target to preprocess a source file
test/MainSystemTest.cpp.i:
	$(MAKE) -f CMakeFiles/ppstee_test_113.dir/build.make CMakeFiles/ppstee_test_113.dir/test/MainSystemTest.cpp.i
	$(MAKE) -f CMakeFiles/ppstee_test_3.dir/build.make CMakeFiles/ppstee_test_3.dir/test/MainSystemTest.cpp.i
.PHONY : test/MainSystemTest.cpp.i

test/MainSystemTest.s: test/MainSystemTest.cpp.s
.PHONY : test/MainSystemTest.s

# target to generate assembly for a file
test/MainSystemTest.cpp.s:
	$(MAKE) -f CMakeFiles/ppstee_test_113.dir/build.make CMakeFiles/ppstee_test_113.dir/test/MainSystemTest.cpp.s
	$(MAKE) -f CMakeFiles/ppstee_test_3.dir/build.make CMakeFiles/ppstee_test_3.dir/test/MainSystemTest.cpp.s
.PHONY : test/MainSystemTest.cpp.s

test/mainTest.o: test/mainTest.cpp.o
.PHONY : test/mainTest.o

# target to build an object file
test/mainTest.cpp.o:
	$(MAKE) -f CMakeFiles/ppstee_test_113.dir/build.make CMakeFiles/ppstee_test_113.dir/test/mainTest.cpp.o
	$(MAKE) -f CMakeFiles/ppstee_test_3.dir/build.make CMakeFiles/ppstee_test_3.dir/test/mainTest.cpp.o
.PHONY : test/mainTest.cpp.o

test/mainTest.i: test/mainTest.cpp.i
.PHONY : test/mainTest.i

# target to preprocess a source file
test/mainTest.cpp.i:
	$(MAKE) -f CMakeFiles/ppstee_test_113.dir/build.make CMakeFiles/ppstee_test_113.dir/test/mainTest.cpp.i
	$(MAKE) -f CMakeFiles/ppstee_test_3.dir/build.make CMakeFiles/ppstee_test_3.dir/test/mainTest.cpp.i
.PHONY : test/mainTest.cpp.i

test/mainTest.s: test/mainTest.cpp.s
.PHONY : test/mainTest.s

# target to generate assembly for a file
test/mainTest.cpp.s:
	$(MAKE) -f CMakeFiles/ppstee_test_113.dir/build.make CMakeFiles/ppstee_test_113.dir/test/mainTest.cpp.s
	$(MAKE) -f CMakeFiles/ppstee_test_3.dir/build.make CMakeFiles/ppstee_test_3.dir/test/mainTest.cpp.s
.PHONY : test/mainTest.cpp.s

tools/googletest-1.6/gmock-gtest-all.o: tools/googletest-1.6/gmock-gtest-all.cc.o
.PHONY : tools/googletest-1.6/gmock-gtest-all.o

# target to build an object file
tools/googletest-1.6/gmock-gtest-all.cc.o:
	$(MAKE) -f CMakeFiles/ppstee_test_113.dir/build.make CMakeFiles/ppstee_test_113.dir/tools/googletest-1.6/gmock-gtest-all.cc.o
	$(MAKE) -f CMakeFiles/ppstee_test_3.dir/build.make CMakeFiles/ppstee_test_3.dir/tools/googletest-1.6/gmock-gtest-all.cc.o
.PHONY : tools/googletest-1.6/gmock-gtest-all.cc.o

tools/googletest-1.6/gmock-gtest-all.i: tools/googletest-1.6/gmock-gtest-all.cc.i
.PHONY : tools/googletest-1.6/gmock-gtest-all.i

# target to preprocess a source file
tools/googletest-1.6/gmock-gtest-all.cc.i:
	$(MAKE) -f CMakeFiles/ppstee_test_113.dir/build.make CMakeFiles/ppstee_test_113.dir/tools/googletest-1.6/gmock-gtest-all.cc.i
	$(MAKE) -f CMakeFiles/ppstee_test_3.dir/build.make CMakeFiles/ppstee_test_3.dir/tools/googletest-1.6/gmock-gtest-all.cc.i
.PHONY : tools/googletest-1.6/gmock-gtest-all.cc.i

tools/googletest-1.6/gmock-gtest-all.s: tools/googletest-1.6/gmock-gtest-all.cc.s
.PHONY : tools/googletest-1.6/gmock-gtest-all.s

# target to generate assembly for a file
tools/googletest-1.6/gmock-gtest-all.cc.s:
	$(MAKE) -f CMakeFiles/ppstee_test_113.dir/build.make CMakeFiles/ppstee_test_113.dir/tools/googletest-1.6/gmock-gtest-all.cc.s
	$(MAKE) -f CMakeFiles/ppstee_test_3.dir/build.make CMakeFiles/ppstee_test_3.dir/tools/googletest-1.6/gmock-gtest-all.cc.s
.PHONY : tools/googletest-1.6/gmock-gtest-all.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... check"
	@echo "... check-style"
	@echo "... doc"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... ppstee"
	@echo "... ppstee_example"
	@echo "... ppstee_test_113"
	@echo "... ppstee_test_3"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... uninstall"
	@echo "... examples/ppstee_example.o"
	@echo "... examples/ppstee_example.i"
	@echo "... examples/ppstee_example.s"
	@echo "... src/ppstee.o"
	@echo "... src/ppstee.i"
	@echo "... src/ppstee.s"
	@echo "... src/ppstee_error.o"
	@echo "... src/ppstee_error.i"
	@echo "... src/ppstee_error.s"
	@echo "... src/ppstee_objects.o"
	@echo "... src/ppstee_objects.i"
	@echo "... src/ppstee_objects.s"
	@echo "... test/MainSystemTest.o"
	@echo "... test/MainSystemTest.i"
	@echo "... test/MainSystemTest.s"
	@echo "... test/mainTest.o"
	@echo "... test/mainTest.i"
	@echo "... test/mainTest.s"
	@echo "... tools/googletest-1.6/gmock-gtest-all.o"
	@echo "... tools/googletest-1.6/gmock-gtest-all.i"
	@echo "... tools/googletest-1.6/gmock-gtest-all.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

